### ISSUE TITLE
Only symbolic links to certain files are placed at /etc/letsencrypt/live/domain.com

### ISSUE THREAD

**Issue by Johnpojohn** [linuxserver/docker-letsencrypt#397] opened 2020-01-07 15:15 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------
I am having an issue when using generated cert files with other containers and applications. It seems the cert generator only places symbolic links in the /live folder, and stores actual files under /archive/domain.com, unfortunately all applications I have tried so far cannot work with this system, and I find myself having to copy cert files manually to other folders to be able to use the container. Is this normal? 

## Expected Behavior
I expected to find cert files under /etc/letsencrypt/live/domain.com

## Current Behavior
Only symbolic links to certain files such as cert.pem are located at /etc/letsencrypt/live/domain.com. I can only see those files while connected to my NAS via SSH, but not using the provided file explorer for example. The files are however visible at /etc/letsencrypt/archive/domain.com as cert1.pem, privkey.pem and so on.

## Environment
Synology DSM with Docker application, x64 architecture

**Comment by aptalca** [comment] 2020-01-07 15:22
The readme contains info on how to share the certs with other apps or containers.

The symlinks are relative and are accessible as long as the other apps/containers have access to the correct path.

Sounds like your samba server does not display symlinks.

Closing this as it is not a bug report. Feel free to drop by our discord or forum if you need further help.

**Closed by aptalca** 2020-01-07 15:22 UTC
