### ISSUE TITLE
iptables allow only cloudflare http/s

### ISSUE THREAD

**Issue by karkaaa** [linuxserver/docker-letsencrypt#466] opened 2020-05-31 18:24 UTC
Hello,

How i can run iptables with rules that allow only cloudflare IPS and drop other http/s after start container?

i add manualy with "docker exec -it letsencrypt /bin/bash"

it is exmaple:
...........
/sbin/iptables -I INPUT -s 131.0.72.0/22 -p tcp --dport 80 -j ACCEPT
/sbin/iptables -I INPUT -s 131.0.72.0/22 -p tcp --dport 443 -j ACCEPT
/sbin/iptables -A INPUT -p tcp --dport 80 -j DROP
/sbin/iptables -A INPUT -p tcp --dport 443 -j DROP

Thank you.

**Comment by aptalca** [comment] 2020-05-31 18:32
https://blog.linuxserver.io/2019/09/14/customizing-our-containers/
closing this because it is not a bug report

**Closed by aptalca** 2020-05-31 18:32 UTC
