### ISSUE TITLE
Small issue upon first startup

### ISSUE THREAD

**Issue by STaRDoGG** [linuxserver/docker-letsencrypt#330] opened 2019-06-26 14:43 UTC
I'm using this container on Docker Desktop (Windows) which is set to run at windows boot, and have all of my containers including this one set with the -restart unless-stopped flag, so they also auto-start at windows boot; for some reason Nginx always errors the first time it tries to start, coughing up this error message:

```
Error determining zone_id: 9103 Unknown X-Auth-Key or X-Auth-Email. Please confirm that you have supplied valid Cloudflare API credentials. (Did you enter the correct email address?)

IMPORTANT NOTES: - Your account credentials have been saved in your Certbot configuration directory at /etc/letsencrypt. You should make a secure backup of this folder now. This configuration directory will also contain certificates and private keys obtained by Certbot so   making regular backups of this folder is ideal. ERROR: Cert does not exist! Please see the validation error above. Make sure you entered correct credentials into the /config/dns-conf/cloudflare.ini file.
```

But w/out making a single change to anything and just clicking the Restart button (in DockStation) it then boots up fine, as usual.

I have the CloudFlare.ini set (in Windows) as ReadOnly, not that I think that would cause an issue with it saying the credentials in it are incorrect(?), and I do know that the credentials are correct in it as well.

Here's the command-line I used to start it:

`docker run --restart always -p 3333:443 -d --name nginx --network=my-bridge --cap-add=NET_ADMIN -e PUID=197609 -e PGID=197121 -e "TZ=America/Chicago" -e "URL=domain.rocks" -e "SUBDOMAINS=mydomain,sourcegraph,grafana,prometheus,resilio-sync,syncthing" -e VALIDATION=dns -e ONLY_SUBDOMAINS=true -e DNSPLUGIN=cloudflare -v "/d/Sites/MyWeb/.config/Nginx:/config" linuxserver/letsencrypt`

Any ideas?

**Comment by aptalca** [comment] 2019-06-26 14:55
It shouldn't try to validate on start if you already have valid certs.

It seems like your docker containers are starting too early before the mount location is ready, so it thinks the config folder is empty.

Google how to delay the docker service on windows so everything else is ready before the containers are started

**Comment by STaRDoGG** [comment] 2019-07-05 04:50
Still battling with this.

Previously, I had the `-v "/d/Sites/MyWeb/.config/Nginx:/config"` on an external USB drive and had the same thought you suggested; that maybe the USB drive wasn't powering up before the Docker daemon.

I've since moved that mount onto an SSD drive (now both Docker Desktop and that config mount are on the same SSD drive, only on 2 different partitions), as well as setting the "Docker Desktop Service" to "Automatic (Delayed)".  I still have the same error upon Window's first boot.

Very strange. I've thought about setting that mount as a volume but that would really make all the constant tweaking of nginx configs a PITA with all the `docker cp` that has to be done after each tweak test. Any other possible suggestions?

**Comment by STaRDoGG** [comment] 2019-07-13 13:30
Just an update on this; I was left w/no choice but to create a volume on the vm for the `/config` and that solved it. Now I'm just left w/having to `docker cp` from the local host to the container with every config tweak. c'est la vie.

**Comment by thelamer** [comment] 2019-07-15 20:44
Closing as this is not a bug report or feature request. 

For continued support please try discord or our forums: 
https://discord.gg/YWrKVTn
https://discourse.linuxserver.io/

We are not able to make any code changes to check for the existence and persistence of the /config volume. We assume it will be available on startup and the data we put there will persist.

**Closed by thelamer** 2019-07-15 20:44 UTC
