### ISSUE TITLE
/config/nginx/.htpasswd" failed (13: Permission denied)

### ISSUE THREAD

**Issue by lelamamalgache** [linuxserver/docker-letsencrypt#420] opened 2020-03-12 11:15 UTC
Hello,

I protect my linuxserver-smokeping with an .htpasswd but still getting 500 error
Could you have a look how i fix it, maybe you could fix it for next user or not

------------------------------

## Steps to Reproduce
1. enable the next two lines for http auth (smokeping)
2. docker exec -it letsencrypt htpasswd -c /config/nginx/.htpasswd myusername
3. restart all containers
4. https://smokeping.domain.fr gets error 500

## Steps to fix (error 500)
1. docker exec -it letsencrypt bash
2. chown abc:abc .htpasswd
3. restart all containers
4. https://smokeping.domain.fr gets error 500
## Steps to fix (error 500)
1. docker exec -it letsencrypt bash
2. chmod 777 .htpasswd
3. restart all containers
4. https://smokeping.domain.fr gets error 500
## Steps to fix (OK)
0. i delete my .htpasswd
1. docker exec -it letsencrypt htpasswd -c /config/nginx/.htpasswd myusername
2. docker exec -it letsencrypt bash
3. chmod 020 to 770 nginx folder
3. restart all containers
4. https://smokeping.domain.fr gets OK

## Docker logs
2020/03/12 11:17:20 [crit] 407#407: *113 open() "/config/nginx/.htpasswd" failed (13: Permission denied), client: 172.19.0.1, server: smokeping.*, request: "GET / HTTP/2.0", host: "smokeping.domai.fr"

## Environment
**OS:**  Synology    
**CPU architecture:** x86_64 

## Command used to create docker container (run/create/compose/screenshot)
letsencrypt
```
docker run -d \
       --name=letsencrypt \
       --cap-add=NET_ADMIN \
       --net=linuxserver \
       -v /volume1/Docker-config/Letsencrypt:/config \
       -e TZ=Europe/Paris \
       -e PUID=1026 \
       -e PGID=100 \
       -e URL=domain.fr \
       -e ONLY_SUBDOMAINS=true \
       -e SUBDOMAINS=sonarr,radarr,jackett,jellyfin,deluge,smokeping \
       -e VALIDATION=ovh \
       -e dns_ovh_endpoint=ovh-eu \
       -e dns_ovh_application_key=1234 \
       -e dns_ovh_application_secret=1234 \
       -e dns_ovh_consumer_key=1234 \
       -p 1443:443 \
       -p 180:80 \
linuxserver/letsencrypt:latest
```
 
 smokeping
```
docker run -d \
       --name=smokeping \
       --net=linuxserver \
       -v /volume1/Docker-config/Smokeping/config:/config \
       -v /volume1/Docker-config/Smokeping/data:/data \
       -e TZ=Europe/Paris \
       -e PUID=1026 \
       -e PGID=100 \
       -p 8080:80 \
linuxserver/smokeping:latest
```
 
smokeping.subdomain.conf
```
# make sure that your dns has a cname set for smokeping
 
server {
    listen 443 ssl;
    listen [::]:443 ssl;
 
    server_name smokeping.*;
 
    include /config/nginx/ssl.conf;
 
    client_max_body_size 0;
 
    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;
 
    location / {
        # enable the next two lines for http auth
        auth_basic "Restricted";
        auth_basic_user_file /config/nginx/.htpasswd;
 
        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /login;
 
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app smokeping;
        set $upstream_port 80;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
 
    }
}
```

**Comment by aptalca** [comment] 2020-03-12 14:05
Went through your posts on discord and you did a lot of chmod/chown prior to the results above. The permissions on the nginx folder should never have been 020, that means even the user who owns it cannot read it. This is likely pebkac and not a bug.

Normally, the htpasswd creation is done as root inside the container and the resulting file is owned by root. That is OK, because the file is world readable. After a container restart, the ownership will change to `abc`.

Closing this now. Feel feel to reopen if you can reproduce on a fresh container without manual chown/chmod

**Closed by aptalca** 2020-03-12 14:05 UTC
