### ISSUE TITLE
LuaJIT error on logs

### ISSUE THREAD

**Issue by a3nick** [linuxserver/docker-letsencrypt#303] opened 2019-05-08 10:14 UTC
I receive an alert on the docker container log related to a `LuaJIT` issue, but the system seems to work correctly
> docker 18.09.0 on raspbian 9.0 (armv7l - rPI)

```
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
        no field package.preload['resty.core']
        no file './resty/core.lua'
        no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core.lua'
        no file '/usr/local/share/lua/5.1/resty/core/init.lua'
        no file '/usr/share/lua/5.1/resty/core.lua'
        no file '/usr/share/lua/5.1/resty/core/init.lua'
        no file '/usr/share/lua/common/resty/core.lua'
        no file '/usr/share/lua/common/resty/core/init.lua'
        no file './resty/core.so'
        no file '/usr/local/lib/lua/5.1/resty/core.so'
        no file '/usr/lib/lua/5.1/resty/core.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './resty.so'
        no file '/usr/local/lib/lua/5.1/resty.so'
        no file '/usr/lib/lua/5.1/resty.so'
        no file '/usr/local/lib/lua/5.1/loadall.so')
```
Thank you

**Comment by aptalca** [comment] 2019-05-08 17:02
Reproduced the issue, looking into it.

Thanks

**Comment by sparklyballs** [comment] 2019-05-10 13:39
i don't think there's a simple fix for this as it stands.

openresty package that satisfies the warnings is a specific compile of nginx with different modules etc.

https://git.alpinelinux.org/aports/tree/testing/openresty/APKBUILD

**Comment by sparklyballs** [comment] 2019-05-10 13:40
openresty added a check for this version with the nginx lua modules version 1.15 which was recently updated from .13 to fix problems in one of the armxx versions

**Comment by VirtualL** [comment] 2019-05-13 16:40
Have the same issue:
```
.....
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)

nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:

no field package.preload['resty.core']
no file './resty/core.lua'
no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua'
no file '/usr/local/share/lua/5.1/resty/core.lua'
no file '/usr/local/share/lua/5.1/resty/core/init.lua'
no file '/usr/share/lua/5.1/resty/core.lua'
no file '/usr/share/lua/5.1/resty/core/init.lua'
no file '/usr/share/lua/common/resty/core.lua'
no file '/usr/share/lua/common/resty/core/init.lua'
no file './resty/core.so'
no file '/usr/local/lib/lua/5.1/resty/core.so'
no file '/usr/lib/lua/5.1/resty/core.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
no file './resty.so'
no file '/usr/local/lib/lua/5.1/resty.so'
no file '/usr/lib/lua/5.1/resty.so'
no file '/usr/local/lib/lua/5.1/loadall.so')
Server ready
```
Runing on Unraid 6.7.0 ,Not getting this error in the previous version (not sure whitch one start this error , but was working ok 10 days ago+-)
Also, everything working good with this error. (No changes made in the config)

**Comment by ethanopp** [comment] 2019-05-16 20:53
+1 causing my home-assistant reverse proxy to fail

**Comment by aptalca** [comment] 2019-05-17 04:23
@ethanopp I highly doubt that. Reverse proxy shouldn't be relying on the lua module. Check your confs

**Comment by ethanopp** [comment] 2019-05-17 10:49
Hmm alright I’ll check but didn’t change anything - just re-pulled and it was working fine before

**Comment by straying1** [comment] 2019-05-18 02:21
Same here.
Ubuntu 18.04.2 LTS.
Running the container via Portainer.

Build date is `BUILD_DATE=2019-05-10T09:17:08-04:00`


```
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)


nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:


	no field package.preload['resty.core']


	no file './resty/core.lua'


	no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua'


	no file '/usr/local/share/lua/5.1/resty/core.lua'


	no file '/usr/local/share/lua/5.1/resty/core/init.lua'


	no file '/usr/share/lua/5.1/resty/core.lua'


	no file '/usr/share/lua/5.1/resty/core/init.lua'


	no file '/usr/share/lua/common/resty/core.lua'


	no file '/usr/share/lua/common/resty/core/init.lua'


	no file './resty/core.so'


	no file '/usr/local/lib/lua/5.1/resty/core.so'


	no file '/usr/lib/lua/5.1/resty/core.so'


	no file '/usr/local/lib/lua/5.1/loadall.so'


	no file './resty.so'


	no file '/usr/local/lib/lua/5.1/resty.so'


	no file '/usr/lib/lua/5.1/resty.so'


	no file '/usr/local/lib/lua/5.1/loadall.so')

Server ready
```

**Comment by CHBMB** [comment] 2019-05-18 08:42
AFAIUI we're dependent on an upstream fix for this @straying1 and it won't affect the workings of the container unless you're specifically using Lua

**Comment by straying1** [comment] 2019-05-18 15:31
That's fine with me, thank you!

**Comment by tomraithel** [comment] 2019-05-23 21:05
I have the same problem. How can I bypass this issue until a fix is provided? I´m currently testing the image on an Amazon EC2 instance with this params:

```
sudo docker run \
  --name=letsencrypt \
  --cap-add=NET_ADMIN \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e URL=foo.com \
  -e SUBDOMAINS=bla \
  -e VALIDATION=http \
  -e EMAIL=xxx@xxxx.com \
  -e DHLEVEL=2048 \
  -e ONLY_SUBDOMAINS=true \
  -p 443:443 \
  -p 80:80 \
  -v le-config:/config \
  --rm \
  -d \
  linuxserver/letsencrypt
```
Output in the error-logs is the same as described above. After that, the container shuts down.

**Comment by aptalca** [comment] 2019-05-23 21:08
@tomraithel that error should not lead to container shut down. In fact, most errors result in a `sleep infinity` in this image. Open a new issue and post a full docker log so we can examine

**Comment by STaRDoGG** [comment] 2019-06-13 20:32
Is there a way to simply silence that error from showing for the time being?

**Comment by aptalca** [comment] 2019-06-13 20:36
https://github.com/openresty/lua-nginx-module/issues/1509#issuecomment-486122328

**Comment by Ryonez** [comment] 2019-06-28 09:08
Is there a way to disable the alert for the LuaJIT version as well?
This is currently slowing down startup speeds like no tomorrow.

**Comment by tobbenb** [comment] 2019-06-28 11:27
@Ryonez 
There is no delay caused by the error messages here, so there must be another reason your container is slow to start.

**Comment by Ryonez** [comment] 2019-06-28 22:36
The slowness only stops once the alert is made. Once it's made, everything comes up instantly. 
It's also present on a completely clean instance, with only the default configs, which is why I asked if this is influencing it.
And it takes around two minutes for the alert to post. Not horrible when you're not doing work, but sadly a pain when testing/changing things.

**Comment by STaRDoGG** [comment] 2019-06-28 23:30
@Ryonez yikes. I have to concur with @tobbenb in that it might be something else. I do still get that LUAJit message but it doesn't cause any slowdown; it's instant. (on my machine).

**Comment by Ryonez** [comment] 2019-06-28 23:33
@STaRDoGG Good to know. I'll keep pokeing at later and see if I can find the cause then.

**Comment by jennec** [comment] 2019-07-02 10:49
I had the exact issue reported here.  Added 1 config file, from one of the templates provided, and suddenly nginx could not start.  I took a look at the site config I just added and noticed this entry:

listen [::]:443 ssl;

I don't use IPv6, so I diabled that entry and restart nginx.  Now nginx is up and running.  Still with the errors listed in the OP.  But at least its working until a fix can be found.

**Comment by nemchik** [comment] 2019-07-02 11:09
Sounds like different issues to me. IPv6 wouldn't have anything to do with the lua error (which is harmless other than log spam). Your system should run fine with the IPv6 configs, they should just be ignored if you don't have IPv6. Anyway I recommend joining the lsio discord if you need further help.

**Comment by djismgaming** [comment] 2019-07-04 03:00
> @STaRDoGG Good to know. I'll keep pokeing at later and see if I can find the cause then.

I removed the `/config/nginx/proxy.conf` file and my errors for proxy_header_size went away upon a container restart because the file was rewritten from the container image on container restart.

Now the proxies work instantaneously. Had a 2 minute delay before.

May help you if you are also getting proxy_header_size issues.

**Comment by tobbenb** [comment] 2019-07-04 09:01
Please don't use this as a support thread. For that we have both Discord and a forum!

**Comment by JOduMonT** [comment] 2019-10-17 07:01
I simply `cp /etc/nginx/modules /config/modules` than change the path into `nginx.conf`
than `rm -Rf /config/modules/*lua*` than restart the container

### My question is
what is the purpose of LUA in this container ?

**Comment by aptalca** [comment] 2019-10-23 19:55
It's a full fledged web server. Some people use lua in serving their content.

**Closed by aptalca** 2019-10-23 19:55 UTC

**Comment by nemchik** [comment] 2019-10-23 20:06
Was this finally fixed upstream? Or is this being closed since nothing can be done in this repo to resolve the issue?

**Comment by aptalca** [comment] 2019-10-23 20:47
Closed because it's not our issue. The nginx maintainer upstream is MIA. But they have the issue open there: https://gitlab.alpinelinux.org/alpine/aports/issues/10478

**Comment by JOduMonT** [comment] 2019-10-26 09:51
@aptalca thank for the anwser, I guess
so if I remove those module and/or I don't use LUA, since I still don't what it is or how to use it
it have no consequence on nginx and this container ?

if it's true, why not putting those configuration optional ?

**Comment by CHBMB** [comment] 2019-10-26 14:01
@JOduMonT If you don't use Lua, then there is no problem.  Rewriting the container to make it optional would only serve to make the logs cleaner, be a ton of added work, for something that has no consequence anyway.

Once upstream fix the issue, it will resolve itself anyways.

**Comment by JOduMonT** [comment] 2019-10-26 17:30
@CHBMB thank for your anwser, I wasnt sure if LUA was playing a role while the Let's Encrypt certificate is generated and/or other task done by this image, but now I understand it's only if I explicitely use LUA.

**Comment by Bill0412** [comment] 2020-06-15 01:28
Disable the module will temporarily solve the issue: https://kickstart.best/fix-lua_load_resty_core-failed-to-load-the-resty-core-module/
