### ISSUE TITLE
disable FPM

### ISSUE THREAD

**Issue by n8tb1t** [linuxserver/docker-letsencrypt#350] opened 2019-08-05 08:32 UTC
I don't need FPM, LUA Fail2Ban, how do I disable all of that ?

**Comment by aptalca** [comment] 2019-08-05 12:04
You don't need to disable them. They use little to no resources when idle.

**Comment by n8tb1t** [comment] 2019-08-05 12:40
@aptalca, thanks for the reply.
I don't use PHP in my workflow, why should I have it? I want to run letsencrypt in host mode, fpm uses port 9000 which, is allocated on my server, I know I can change the FPM port in configs, but after all, I need letsencrypt in bare bone package, without bells and whistles. 
I found a simple solution after all from `DanielDent/docker-nginx-ssl-proxy`

**Comment by aptalca** [comment] 2019-08-05 12:51
What is the reason for running it with host networking?

**Comment by nemchik** [comment] 2019-08-05 12:52
If you're running the container in bridge mode you can just not add the 9000 port to the container and your system can use 9000 for something else.

The image is built to have everything you might need, but you're not required to use all of it. The extras that you don't use are not the kinds of things that you'll see and performance hit from, so simply ignore them and use what you want. Being minimal wouldn't have any tangible benefit in this case.

**Comment by CHBMB** [comment] 2019-08-14 18:26
Closing this, not a bug or issue.

**Closed by CHBMB** 2019-08-14 18:26 UTC
